/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

double*
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = arg1 + arg2;
	return &result;
}

double *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = arg1 - arg2;
	return &result;
}

double *
multiplicacion_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = arg1 * arg2;
	return &result;
}

double *
division_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = (arg1 + 0.0) / arg2;	//obtendriamos los decimales ya que es un double con el 0.0
	return &result;
}

t_array *
sumavectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] + b.t_array_val[i];
	}

	return &result;
}

t_array *
restvectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] - b.t_array_val[i];
	}

	return &result;
}

t_array *
multiplicacionvectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] * b.t_array_val[i];
	}

	return &result;
}

t_array *
divisionvectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] / b.t_array_val[i];
	}

	return &result;
}

funcion *
sumafunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x = f1.x + f2.x;
	result.y = f1.y + f2.y;
	result.z = f1.z + f2.z;

	return &result;
}

funcion *
restafunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x = f1.x - f2.x;
	result.y = f1.y - f2.y;
	result.z = f1.z - f2.z;

	return &result;
}

funcion *
multiplicacionfunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x = f1.x * f2.x;
	result.y = f1.y * f2.y;
	result.z = f1.z * f2.z;

	return &result;
}

funcion *
divisionfunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x = f1.x / f2.x;
	result.y = f1.y / f2.y;
	result.z = f1.z / f2.z;

	return &result;
}

funcion *
derivadafunciones_1_svc(funcion f1,  struct svc_req *rqstp)
{
	static funcion result;

	result.z = f1.y ;
	result.y = f1.x * 2;
	result.x = 0;

	return &result;
}

funcion *
integralfunciones_1_svc(funcion f1,  struct svc_req *rqstp)
{
	static funcion  result;

	result.exponente_x = f1.exponente_x + 1;
	result.x = f1.exponente_x / result.exponente_x;

	result.exponente_y = f1.exponente_y + 1;
	result.y = f1.exponente_y / result.exponente_y;

	result.exponente_z = f1.exponente_z + 1;
	result.z = f1.exponente_z / result.exponente_z;


	return &result;
}
