/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

double*
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = arg1 + arg2;
	return &result;
}

double *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = arg1 - arg2;
	return &result;
}

double *
multiplicacion_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = arg1 * arg2;
	return &result;
}

double *
division_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result;
	result = (arg1 + 0.0) / arg2;	//obtendriamos los decimales ya que es un double con el 0.0
	return &result;
}

t_array *
sumavectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] + b.t_array_val[i];
	}

	return &result;
}

t_array *
restvectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] - b.t_array_val[i];
	}

	return &result;
}

t_array *
multiplicacionvectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] * b.t_array_val[i];
	}

	return &result;
}

t_array *
divisionvectores_1_svc(t_array a, t_array b, int n,  struct svc_req *rqstp)
{
	static t_array  result;	//static OJO
	result.t_array_len = n;
	result.t_array_val = malloc(n*sizeof(double));

	for(int i = 0; i < result.t_array_len; i++)
	{
		result.t_array_val[i] = a.t_array_val[i] / b.t_array_val[i];
	}

	return &result;
}

funcion *
sumafunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x2 = f1.x2 + f2.x2;
	result.x = f1.x + f2.x;
	result.valor = f1.valor + f2.valor;

	return &result;
}

funcion *
restafunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x2 = f1.x2 - f2.x2;
	result.x = f1.x - f2.x;
	result.valor = f1.valor - f2.valor;

	return &result;
}

funcion *
multiplicacionfunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x2 = f1.x2 * f2.x2;
	result.x = f1.x * f2.x;
	result.valor = f1.valor * f2.valor;

	return &result;
}

funcion *
divisionfunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion result;

	result.x2 = f1.x2 / f2.x2;
	result.x = f1.x / f2.x;
	result.valor = f1.valor / f2.valor;

	return &result;
}

funcion *
derivadafunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion  result;

	/*
	 * insert server code here
	 */

	return &result;
}

funcion *
integralfunciones_1_svc(funcion f1, funcion f2,  struct svc_req *rqstp)
{
	static funcion  result;

	/*
	 * insert server code here
	 */

	return &result;
}
